server:
  port: 9000
  error:
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: localhost
    port: 6379
    password:

  cache:
    type: redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: service-swagger

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

mybatis:
  table:
    auto: update

  model:
    pack: com.example.backend.entity
